name: football-etl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip>=23.0
  - jupyter>=1.0
  - notebook>=7.0
  - jupyterlab>=4.0
  - pandas>=2.1
  - numpy>=1.26
  - matplotlib>=3.8
  - seaborn>=0.13
  - requests>=2.31
  - beautifulsoup4>=4.12
  - sqlalchemy>=2.0
  - pip:
    - python-dotenv>=1.0.0
